### user login (id, password)
POST http://localhost:8080/api/auth/member
Content-Type: application/json; charset=UTF-8
Accept: */*

{
  "id": "1212",
  "password":"1212"
}

### store login(id, password)
POST http://localhost:8080/api/auth/store
Content-Type: application/json; charset=UTF-8
Accept: */*

{
  "id": "s2222",
  "password":"2222"
}