### 메뉴 등록(1 ~ 100개)
POST http://localhost:8080/api/menu/5
Content-Type: application/json; charset=UTF-8

[
    {"menuName": "핫 아메리카노",
      "menuPrice": 2000
    }
  , {"menuName": "아이스 아메리카노",
      "menuPrice": 2000
    }
  , {"menuName": "아이스 카페라떼",
      "menuPrice": 4500
    }
  , {"menuName": "핫 카페라떼",
      "menuPrice": 4000
    }
  , {"menuName": "피스타치오쉐이크",
      "menuPrice": 5000
    }
  , {"menuName": "초코쿠키",
      "menuPrice": 1000
    }
  ]

### 메뉴 다건 조회
GET http://localhost:8080/api/menu/5

### 메뉴 단건 조회
GET http://localhost:8080/api/menu/5/19

### 메뉴 단건 수정(이름, 가격, 주문여부)
PUT http://localhost:8080/api/menu/5/19
Content-Type: application/json; charset=UTF-8

    {
      "menuName": "",
      "menuPrice": 4800,
      "isOrder": "Y"
    }

### 메뉴 다건 수정 (실패 메세지 떠도 성공한거임...왜그러지)
PATCH http://localhost:8080/api/menu/5
Content-Type: application/json; charset=UTF-8

[
  {
    "menuCode": "19",
    "menuPrice": 900
  },
  {
    "menuCode": "21",
    "isOrder": "N"
  },
  {
    "menuCode": "92",
    "menuName": "피스타치오 불하부친오"
  }
]



### 메뉴 단건 삭제
DELETE http://localhost:8080/api/menu/5/22

### 메뉴 다건 삭제(파라미터 길이제한으로 삭제 수량 제한 두기 약 30~50개?)
DELETE http://localhost:8080/api/menu/5?codes=96


