### ORDERS-1. 선택 메뉴 주문
POST http://localhost:8080/api/orders/order
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "code": 2,
  "sCode": 5,
  "status": "접수",
  "orderMenuList":[
    {
    "menuCode": "91",
    "amount": 1,
      "menuPrice": 4000
    },
    {
      "menuCode": "92",
      "amount": 2,
      "menuPrice": 5000
    }
  ]
}

### ORDERS-2. 주문상태 변경 (접수>진행중>제조완료>픽업완료)
PUT http://localhost:8080/api/orders/process
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

//{
//  "sCode": 5,
//  "orderCode": "20231201-0058",
//  "status": "진행중"
//}

//{
//  "sCode": 5,
//  "orderCode": "20231201-0058",
//  "status": "제조완료"
//}

{
  "sCode": 5,
  "orderCode": "20231201-0058",
  "status": "픽업완료"
}

### ORDERS-3. 주문내역 조회 @RequestParam 사용
GET http://localhost:8080/api/orders/search?code=1111
Content-Type: application/json

### ORDERS-4. 주문내역 상세조회 @PathVariable 사용
GET http://localhost:8080/api/orders/search/detail/20231201-0057
Content-Type: application/json

### ORDERS-5. 주문상태 조회 @RequestParam 사용
GET http://localhost:8080/api/orders/status/20231201-0057
Content-Type: application/json
