### ORDERS-1. 선택 메뉴 주문
POST http://localhost:8080/api/orders/order
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "code": 1111,
  "sCode": 4,
  "status": "접수",
  "orderMenuList":[
    {
    "menuCode": "37",
    "amount": 1,
    "menuPrice": 1500
    },
    {
      "menuCode": "38",
      "amount": 3,
      "menuPrice": 4000
    }
  ]
}

### ORDERS-2. 주문상태 변경 (접수>진행중>제조완료>픽업완료)
PUT http://localhost:8080/api/orders/process
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "sCode": 0,
  "orderCode": "20231130-0054",
  "status": "진행중"
}

### ORDERS-3. 주문내역 조회 @RequestParam 사용
GET http://localhost:8080/api/orders/search?code=1111
Content-Type: application/json

### ORDERS-4. 주문내역 상세조회 @PathVariable 사용
GET http://localhost:8080/api/orders/search/detail/20231130-0054
Content-Type: application/json
